import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import axios from 'axios'
import { HiOutlineIdentification } from 'react-icons/hi'
import Layout from '../../components/Layout'
import {
  BackIcon,
  Card,
  CardDataWrapper,
  CardIcon,
  CardsWrapper,
  Container,
  Content,
  Data,
  DataTitle,
  Email,
  Label,
  Option,
  PageTitle,
  PageTitleWrapper,
  SectionOrganizationalData,
  SectionTitle,
  Select,
  SelectContainer,
  SelectsContainerWrapper,
  SelectsRow,
  UserContainer,
  UserData,
  Username,
  Wrapper,
} from '../../styles/home'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { AiOutlineArrowLeft } from 'react-icons/ai'
import Image from 'next/image'
import { BiPhoneCall } from 'react-icons/bi'
import { FiCalendar } from 'react-icons/fi'

interface Phone {
  ddd: number
  ddi: number
  number: number
}
interface Document {
  type: string
  number: number
}
interface Agent {
  id: number
  name: string
  image: string
  department: string
  branch: string
  role: string
  status: boolean
  email: string
  phone: Phone
  document: Document
  birth_date: Date
}

interface MainProps {
  data: Agent
}
const Colaborador: React.FC<MainProps> = ({ data }) => {
  const router = useRouter()
  const transformCPF = (text: string) => {
    const badchars = /[^\d]/g
    const mask = /(\d{3})(\d{3})(\d{3})(\d{2})/
    const cpf = new String(text).replace(badchars, '')
    return cpf.replace(mask, '$1.$2.$3-$4')
  }
  return (
    <div>
      <Head>
        <title>Detalhes do Colaborador</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Wrapper>
          <Container>
            <PageTitleWrapper>
              <Link href='/'>
                <BackIcon>
                  <AiOutlineArrowLeft />
                </BackIcon>
              </Link>
              <PageTitle>Detalhes do colaborador</PageTitle>
            </PageTitleWrapper>
            <Content>
              <UserContainer>
                <Image
                  src={data.image}
                  layout='fixed'
                  height={80}
                  width={80}
                  objectFit='cover'
                  alt='avatar'
                  style={{ borderRadius: '50%' }}
                />
                <UserData>
                  <Username>{data.name}</Username>
                  <Email>{data.email}</Email>
                </UserData>
              </UserContainer>
              <SectionTitle>Informações pessoais</SectionTitle>
              <CardsWrapper>
                <Card>
                  <CardIcon>
                    <HiOutlineIdentification size={20} />
                  </CardIcon>
                  <CardDataWrapper>
                    <DataTitle>{data.document.type}</DataTitle>
                    <Data>{transformCPF(data.document.number.toString())}</Data>
                  </CardDataWrapper>
                </Card>
                <Card>
                  <CardIcon>
                    <BiPhoneCall size={20} />
                  </CardIcon>
                  <CardDataWrapper>
                    <DataTitle>Telefone</DataTitle>
                    <Data>{`+${data.phone.ddi} ${data.phone.ddd} ${data.phone.number}`}</Data>
                  </CardDataWrapper>
                </Card>
                <Card>
                  <CardIcon>
                    <FiCalendar size={20} />
                  </CardIcon>
                  <CardDataWrapper>
                    <DataTitle>Nascimento</DataTitle>
                    <Data>{new Date(data.birth_date).toLocaleDateString()}</Data>
                  </CardDataWrapper>
                </Card>
              </CardsWrapper>
              <SectionOrganizationalData>
                <SectionTitle>Dados Organizacionais</SectionTitle>
                <SelectsContainerWrapper>
                  <SelectsRow>
                    <SelectContainer>
                      <Label>Departamento</Label>
                      <Select>
                        <Option>Comercial</Option>
                      </Select>
                    </SelectContainer>
                    <SelectContainer>
                      <Label>Cargo</Label>
                      <Select>
                        <Option>Gerente</Option>
                      </Select>
                    </SelectContainer>
                  </SelectsRow>
                  <SelectsRow>
                    <SelectContainer>
                      <Label>Unidade</Label>
                      <Select>
                        <Option>Unidade 1</Option>
                      </Select>
                    </SelectContainer>
                    <SelectContainer>
                      <Label>Status</Label>
                      <Select>
                        <Option>Ativo</Option>
                      </Select>
                    </SelectContainer>
                  </SelectsRow>
                </SelectsContainerWrapper>
              </SectionOrganizationalData>
            </Content>
          </Container>
        </Wrapper>
      </Layout>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async context => {
  const { data } = await axios.get('https://pp-api-desafio.herokuapp.com/agent/1')
  return {
    props: {
      data: data.agent,
    },
  }
}

export default Colaborador
