import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState } from 'react'
import TableDrop from '../components/TableToDropdown'
import { BsThreeDotsVertical } from 'react-icons/bs'
import Layout from '../components/Layout'
import {
  BottomContainerSingle,
  Container,
  Content,
  ListTitle,
  PageTitle,
  Wrapper,
} from '../styles/cargos'
import Link from 'next/link'
import { useRouter } from 'next/router'
import SearchInput from '../components/SearchInput'
import Pagination from '../components/Pagination'
import { AiOutlineEye, AiOutlineFileAdd } from 'react-icons/ai'
import { RiDeleteBinLine } from 'react-icons/ri'
import { FiEdit } from 'react-icons/fi'
import { ImStack } from 'react-icons/im'
import SelectModal from '../components/SelectModal'
import { MdOutlineKeyboardArrowDown, MdOutlineKeyboardArrowUp } from 'react-icons/md'
import Tabs from '../components/Tabs'
import {
  ActionLabel,
  DropdownIcon,
  Value,
  Label,
  ActionsContainer,
  DotsIcon,
} from '../components/TableToDropdown/styles'
import ModalOptions from '../components/ModalOptions'
interface Roles {
  name: string
  departament: string
  agents_quantity: number
}
interface MainProps {
  data: [Roles]
}

interface IsOpenList {
  [key: string]: boolean
}
const Cargos: React.FC<MainProps> = ({ data }) => {
  const [displayData, setDisplayData] = useState(data)
  const [modalCategoriesIsOpen, setModalCategoriesIsOpen] = useState(false)
  const [modalIsOpenList, setModalIsOpenList] = useState<IsOpenList>({})
  const [dropdownIsOpenList, setDropdownIsOpenList] = useState<IsOpenList>({})
  const router = useRouter()

  useEffect(() => {
    const modalList = displayData.reduce((prev, curr) => {
      return { ...prev, [curr.name + curr.departament]: false }
    }, {})
    setModalIsOpenList(modalList)
  }, [displayData])

  const toggleModal = (key: string) => {
    let newList = { ...modalIsOpenList }
    Object.keys(newList).forEach(item => (newList[item] = false))
    newList[key] = true
    setModalIsOpenList(newList)
  }
  const toggleDropdown = (id: string) => {
    let newList = { ...dropdownIsOpenList }
    if (newList[id]) {
      Object.keys(newList).forEach(item => (newList[item] = false))
    } else {
      Object.keys(newList).forEach(item => (newList[item] = false))
      newList[id] = !newList[id]
    }
    setDropdownIsOpenList(newList)
  }
  const anyModalOpen = () => {
    let isOpen = false
    Object.keys(modalIsOpenList).forEach(item => {
      if (modalIsOpenList[item]) {
        isOpen = true
      }
    })
    return isOpen
  }
  const closeModal = () => {
    if (anyModalOpen()) {
      let newList = { ...modalIsOpenList }
      Object.keys(newList).forEach(item => (newList[item] = false))
      setModalIsOpenList(newList)
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Wrapper onClick={closeModal}>
          <Container>
            <PageTitle>Organização</PageTitle>
            <Content>
              <Tabs>
                <Tabs.Tab url='/' isActive={router.pathname === '/'}>
                  Colaboradores
                </Tabs.Tab>
                <Tabs.Tab url='/cargos' isActive={router.pathname !== '/'}>
                  Cargos
                </Tabs.Tab>
              </Tabs>
              <SelectModal
                isOpen={modalCategoriesIsOpen}
                openFn={() => setModalCategoriesIsOpen(true)}
                closeFn={() => setModalCategoriesIsOpen(false)}
                label={'Cargos'}
              />
              <SearchInput />
              <ListTitle>Listagem de cargos</ListTitle>
              {data && (
                <TableDrop>
                  <TableDrop.Header>
                    <TableDrop.Row>
                      <TableDrop.Th>Cargo</TableDrop.Th>
                      <TableDrop.Th>Departamento</TableDrop.Th>
                      <TableDrop.Th>Colaboradores</TableDrop.Th>
                      <TableDrop.Th></TableDrop.Th>
                    </TableDrop.Row>
                  </TableDrop.Header>
                  <TableDrop.Body>
                    {data.map(role => (
                      <TableDrop.Row
                        key={role.name + role.departament}
                        isActive={dropdownIsOpenList[role.name + role.departament]}
                        maxHeight={'70px'}
                      >
                        <TableDrop.Td onClick={() => toggleDropdown(role.name + role.departament)}>
                          <Label>Cargo</Label>
                          <Value>{role.name}</Value>
                          <DropdownIcon>
                            {!dropdownIsOpenList[role.name + role.departament] ? (
                              <MdOutlineKeyboardArrowDown />
                            ) : (
                              <MdOutlineKeyboardArrowUp />
                            )}
                          </DropdownIcon>
                        </TableDrop.Td>
                        <TableDrop.Td>
                          <Label>Departamento</Label>
                          <Value>{role.departament}</Value>
                        </TableDrop.Td>
                        <TableDrop.Td>
                          <Label>Colaboradores</Label>
                          <Value>{role.agents_quantity}</Value>
                        </TableDrop.Td>
                        <TableDrop.Td>
                          <DotsIcon onClick={() => toggleModal(role.name + role.departament)}>
                            <BsThreeDotsVertical size={16} />
                          </DotsIcon>
                          <ActionsContainer
                            onClick={() => toggleModal(role.name + role.departament)}
                          >
                            <AiOutlineFileAdd size={24} color='#1DD195' />
                            <ActionLabel>Ações</ActionLabel>
                          </ActionsContainer>
                          <ModalOptions isOpen={modalIsOpenList[role.name + role.departament]}>
                            <ModalOptions.Option
                              Icon={AiOutlineEye}
                              url={'/cargo/create'}
                              isActive={true}
                            >
                              Ver cargo
                            </ModalOptions.Option>
                            <ModalOptions.Option
                              Icon={FiEdit}
                              url={'/cargo/create'}
                              isActive={false}
                            >
                              Editar
                            </ModalOptions.Option>
                            <ModalOptions.Option
                              Icon={ImStack}
                              url={'/cargo/create'}
                              isActive={false}
                            >
                              Duplicar
                            </ModalOptions.Option>
                            <ModalOptions.Option
                              Icon={RiDeleteBinLine}
                              url={'/cargo/create'}
                              isActive={false}
                            >
                              Excluir
                            </ModalOptions.Option>
                          </ModalOptions>
                        </TableDrop.Td>
                      </TableDrop.Row>
                    ))}
                  </TableDrop.Body>
                </TableDrop>
              )}
              <BottomContainerSingle>
                <Pagination />
              </BottomContainerSingle>
            </Content>
          </Container>
        </Wrapper>
      </Layout>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async context => {
  const { data } = await axios.get('https://pp-api-desafio.herokuapp.com/roles')
  return {
    props: {
      data: data.roles,
    },
  }
}

export default Cargos
