import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import axios from 'axios'
import { useEffect,  useState } from 'react'
import Table from '../components/Table/index'
import { BsThreeDotsVertical } from 'react-icons/bs'
import Layout from '../components/Layout'
import {
  BottomContainer,
  BottomContainerSingle,
  Container,
  Content,
  ListTitle,
  ModalButton,
  ModalMenu,
  ModalOption,
  ModalOptionIcon,
  ModalOptionLink,
  PageTitle,
  Tab,
  Tabs,
  Wrapper,
} from './home'
import Link from 'next/link'
import { useRouter } from 'next/router'
import SearchInput from '../components/SearchInput'
import Pagination from '../components/Pagination'
import { AiOutlineEye } from 'react-icons/ai'
import { RiDeleteBinLine } from 'react-icons/ri'
interface Roles {
  name: string
  departament: string
  agents_quantity: number
}
interface MainProps {
  data: [Roles]
}

interface ModalIsOpenList {
  [key: string]: boolean
}
const Cargos: React.FC<MainProps> = ({ data }) => {
  const [displayData, setDisplayData] = useState(data)
  const [modalIsOpenList, setModalIsOpenList] = useState<ModalIsOpenList>({})
  const router = useRouter()

  useEffect(() => {
    const modalList = displayData.reduce((prev, curr) => {
      return { ...prev, [curr.name+curr.departament]: false }
    }, {})
    setModalIsOpenList(modalList)
  }, [displayData])

  const toggleModal = (key: string) => {
    let newList = { ...modalIsOpenList }
    Object.keys(newList).forEach(item => (newList[item] = false))
    newList[key] = true
    setModalIsOpenList(newList)
  }
  const anyModalOpen = () => {
    let isOpen = false
    Object.keys(modalIsOpenList).forEach(item => {
      if (modalIsOpenList[item]) {
        isOpen = true
      }
    })
    return isOpen
  }
  const closeModal = () => {
    if (anyModalOpen()) {
      let newList = { ...modalIsOpenList }
      Object.keys(newList).forEach(item => (newList[item] = false))
      setModalIsOpenList(newList)
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Wrapper onClick={closeModal}>
          <Container>
            <PageTitle>Organização</PageTitle>
            <Content>
              <Tabs>
                <Link href='/'>
                  <Tab isActive={router.pathname === '/'}>Colaboradores</Tab>
                </Link>
                <Link href='/cargos'>
                  <Tab isActive={router.pathname !== '/'}>Cargos</Tab>
                </Link>
              </Tabs>
              <SearchInput />
              <ListTitle>Listagem de cargos</ListTitle>
              {data && (
                <Table>
                  <Table.Header>
                    <Table.Row>
                      <Table.Th>Cargo</Table.Th>
                      <Table.Th>Departamento</Table.Th>
                      <Table.Th>Colaboradores</Table.Th>
                      <Table.Th></Table.Th>
                    </Table.Row>
                  </Table.Header>
                  <Table.Body>
                    {data.map(role => (
                      <Table.Row key={role.name + role.departament}>
                        <Table.Td>{role.name}</Table.Td>
                        <Table.Td>{role.departament}</Table.Td>
                        <Table.Td>{role.agents_quantity}</Table.Td>
                        <Table.Td>
                          <ModalButton onClick={() => toggleModal(role.name+role.departament)}>
                            <BsThreeDotsVertical size={16} />
                          </ModalButton>

                          {modalIsOpenList[role.name+role.departament] && (
                            <ModalMenu>
                              <Link href={`/role/1`}>
                                <ModalOption>
                                  <ModalOptionIcon>
                                    <AiOutlineEye size={22} />
                                  </ModalOptionIcon>

                                  <ModalOptionLink isActive={true}>Ver cargo</ModalOptionLink>
                                </ModalOption>
                              </Link>
                              <Link href='#'>
                                <ModalOption>
                                  <ModalOptionIcon>
                                    <RiDeleteBinLine size={22} />
                                  </ModalOptionIcon>

                                  <ModalOptionLink isActive={false}>Excluir</ModalOptionLink>
                                </ModalOption>
                              </Link>
                            </ModalMenu>
                          )}
                        </Table.Td>
                      </Table.Row>
                    ))}
                  </Table.Body>
                </Table>
              )}
              <BottomContainerSingle>
                <Pagination />
              </BottomContainerSingle>
            </Content>
          </Container>
        </Wrapper>
      </Layout>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async context => {
  const { data } = await axios.get('https://pp-api-desafio.herokuapp.com/roles')
  return {
    props: {
      data: data.roles,
    },
  }
}

export default Cargos
